# Generated by Django 5.0 on 2024-02-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristreview',
            name='images',
        ),
        migrations.AddField(
            model_name='touristreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/review_images/'),
        ),
    ]
