# Generated by Django 5.0 on 2024-03-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URL',
        ),
    ]
