# Generated by Django 5.0 on 2024-02-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_alter_register_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin_table',
            },
        ),
    ]
