# Generated by Django 5.0 on 2024-03-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0005_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URL',
        ),
    ]
